//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JetBanjo.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources_da_DK {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_da_DK() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("JetBanjo.Resx.AppResources.da-DK", typeof(AppResources_da_DK).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        public static string avatar {
            get {
                return ResourceManager.GetString("avatar", resourceCulture);
            }
        }
        
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        public static string cannot_detect_backend {
            get {
                return ResourceManager.GetString("cannot_detect_backend", resourceCulture);
            }
        }
        
<<<<<<< Updated upstream
        public static string change_room {
            get {
                return ResourceManager.GetString("change_room", resourceCulture);
            }
        }
        
        public static string choose_room {
            get {
                return ResourceManager.GetString("choose_room", resourceCulture);
            }
        }
        
=======
>>>>>>> Stashed changes
        public static string download_err {
            get {
                return ResourceManager.GetString("download_err", resourceCulture);
            }
        }
        
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        public static string example_ip {
            get {
                return ResourceManager.GetString("example_ip", resourceCulture);
            }
        }
        
<<<<<<< Updated upstream
        public static string example_room {
            get {
                return ResourceManager.GetString("example_room", resourceCulture);
            }
        }
        
=======
>>>>>>> Stashed changes
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        public static string ip {
            get {
                return ResourceManager.GetString("ip", resourceCulture);
            }
        }
        
        public static string ip_null_or_empty_err_msg {
            get {
                return ResourceManager.GetString("ip_null_or_empty_err_msg", resourceCulture);
            }
        }
        
<<<<<<< Updated upstream
        public static string ip_settings {
            get {
                return ResourceManager.GetString("ip_settings", resourceCulture);
            }
        }
        
=======
>>>>>>> Stashed changes
        public static string ip_text {
            get {
                return ResourceManager.GetString("ip_text", resourceCulture);
            }
        }
        
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        public static string remove_ip {
            get {
                return ResourceManager.GetString("remove_ip", resourceCulture);
            }
        }
        
        public static string remove_room {
            get {
                return ResourceManager.GetString("remove_room", resourceCulture);
            }
        }
        
        public static string room {
            get {
                return ResourceManager.GetString("room", resourceCulture);
            }
        }
        
        public static string room_selector {
            get {
                return ResourceManager.GetString("room_selector", resourceCulture);
            }
        }
        
<<<<<<< Updated upstream
        public static string room_settings {
            get {
                return ResourceManager.GetString("room_settings", resourceCulture);
            }
        }
        
=======
>>>>>>> Stashed changes
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
    }
}
