//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JetBanjo.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JetBanjo.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Battle.
        /// </summary>
        internal static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar.
        /// </summary>
        internal static string avatar {
            get {
                return ResourceManager.GetString("avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot detect the server on the local network, you need to manually input it.
        /// </summary>
        internal static string cannot_detect_backend {
            get {
                return ResourceManager.GetString("cannot_detect_backend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download, check internet connection.
        /// </summary>
        internal static string download_err {
            get {
                return ResourceManager.GetString("download_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 127.0.0.1.
        /// </summary>
        internal static string example_ip {
            get {
                return ResourceManager.GetString("example_ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP address.
        /// </summary>
        internal static string ip {
            get {
                return ResourceManager.GetString("ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ip field must be specified for this app to work.
        /// </summary>
        internal static string ip_null_or_empty_err_msg {
            get {
                return ResourceManager.GetString("ip_null_or_empty_err_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input the IP address of the server.
        /// </summary>
        internal static string ip_text {
            get {
                return ResourceManager.GetString("ip_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the window.
        /// </summary>
        internal static string issue_co2 {
            get {
                return ResourceManager.GetString("issue_co2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is dry drink water.
        /// </summary>
        internal static string issue_hum_dry {
            get {
                return ResourceManager.GetString("issue_hum_dry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If its raining close the window.
        /// </summary>
        internal static string issue_hum_wet {
            get {
                return ResourceManager.GetString("issue_hum_wet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close courtains or turn down the light.
        /// </summary>
        internal static string issue_light_bright {
            get {
                return ResourceManager.GetString("issue_light_bright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watching movie? Else remove courtains or turn on the light.
        /// </summary>
        internal static string issue_light_dark {
            get {
                return ResourceManager.GetString("issue_light_dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is too much noise in the room.
        /// </summary>
        internal static string issue_noise {
            get {
                return ResourceManager.GetString("issue_noise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues.
        /// </summary>
        internal static string issue_page {
            get {
                return ResourceManager.GetString("issue_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close windows.
        /// </summary>
        internal static string issue_temp_cold {
            get {
                return ResourceManager.GetString("issue_temp_cold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open windows and a door.
        /// </summary>
        internal static string issue_temp_fire {
            get {
                return ResourceManager.GetString("issue_temp_fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close windows and turn up the heat.
        /// </summary>
        internal static string issue_temp_ice {
            get {
                return ResourceManager.GetString("issue_temp_ice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open windows.
        /// </summary>
        internal static string issue_temp_sweat {
            get {
                return ResourceManager.GetString("issue_temp_sweat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close courtains or apply sunscreen .
        /// </summary>
        internal static string issue_uv {
            get {
                return ResourceManager.GetString("issue_uv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the bad air comming from the outside? Then close the windows, else open windows and doors.
        /// </summary>
        internal static string issue_voc {
            get {
                return ResourceManager.GetString("issue_voc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove IP.
        /// </summary>
        internal static string remove_ip {
            get {
                return ResourceManager.GetString("remove_ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove room.
        /// </summary>
        internal static string remove_room {
            get {
                return ResourceManager.GetString("remove_room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        internal static string room {
            get {
                return ResourceManager.GetString("room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Room.
        /// </summary>
        internal static string room_selector {
            get {
                return ResourceManager.GetString("room_selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
    }
}
