//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JetBanjo.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JetBanjo.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Battle.
        /// </summary>
        internal static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar.
        /// </summary>
        internal static string avatar {
            get {
                return ResourceManager.GetString("avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot detect the server on the local network, you need to manually input it.
        /// </summary>
        internal static string cannot_detect_backend {
            get {
                return ResourceManager.GetString("cannot_detect_backend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change room.
        /// </summary>
        internal static string change_room {
            get {
                return ResourceManager.GetString("change_room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Room.
        /// </summary>
        internal static string choose_room {
            get {
                return ResourceManager.GetString("choose_room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download, check internet connection.
        /// </summary>
        internal static string download_err {
            get {
                return ResourceManager.GetString("download_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 127.0.0.1.
        /// </summary>
        internal static string example_ip {
            get {
                return ResourceManager.GetString("example_ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room 0.1.2.
        /// </summary>
        internal static string example_room {
            get {
                return ResourceManager.GetString("example_room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string infopage {
            get {
                return ResourceManager.GetString("infopage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP address.
        /// </summary>
        internal static string ip {
            get {
                return ResourceManager.GetString("ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ip field must be specified for this app to work.
        /// </summary>
        internal static string ip_null_or_empty_err_msg {
            get {
                return ResourceManager.GetString("ip_null_or_empty_err_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP settings.
        /// </summary>
        internal static string ip_settings {
            get {
                return ResourceManager.GetString("ip_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input the IP address of the server.
        /// </summary>
        internal static string ip_text {
            get {
                return ResourceManager.GetString("ip_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open windows and doors to ensure drafts.
        /// </summary>
        internal static string issue_co2_severe {
            get {
                return ResourceManager.GetString("issue_co2_severe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the window.
        /// </summary>
        internal static string issue_co2_soft {
            get {
                return ResourceManager.GetString("issue_co2_soft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close windows and doors to prevent drafts.
        /// </summary>
        internal static string issue_hum_dry {
            get {
                return ResourceManager.GetString("issue_hum_dry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to place a glass of water in the sun so it can evaporate, it helps to close the curtains, doors and windows..
        /// </summary>
        internal static string issue_hum_dry_temp_high {
            get {
                return ResourceManager.GetString("issue_hum_dry_temp_high", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close windows and doors to prevent drafts.
        /// </summary>
        internal static string issue_hum_dry_temp_low {
            get {
                return ResourceManager.GetString("issue_hum_dry_temp_low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open windows and doors to ensure drafts.
        /// </summary>
        internal static string issue_hum_wet {
            get {
                return ResourceManager.GetString("issue_hum_wet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open windows and doors to ensure drafts or use an air conditioner.
        /// </summary>
        internal static string issue_hum_wet_temp_high {
            get {
                return ResourceManager.GetString("issue_hum_wet_temp_high", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase the temperature by turning on a radiator or something similar..
        /// </summary>
        internal static string issue_hum_wet_temp_low {
            get {
                return ResourceManager.GetString("issue_hum_wet_temp_low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the curtains.
        /// </summary>
        internal static string issue_light_bright {
            get {
                return ResourceManager.GetString("issue_light_bright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you watching a movie? Otherwise remove curtains or turn on the light.
        /// </summary>
        internal static string issue_light_dark {
            get {
                return ResourceManager.GetString("issue_light_dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is too much noise in the room, stop trying to compete in volume, if the noise comes from the outside try to close doors and windows.
        /// </summary>
        internal static string issue_noise {
            get {
                return ResourceManager.GetString("issue_noise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues.
        /// </summary>
        internal static string issue_page {
            get {
                return ResourceManager.GetString("issue_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure that the windows are closed.
        /// </summary>
        internal static string issue_temp_cold {
            get {
                return ResourceManager.GetString("issue_temp_cold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the windows.
        /// </summary>
        internal static string issue_temp_fire {
            get {
                return ResourceManager.GetString("issue_temp_fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure that the windows are closed and turn up the heat.
        /// </summary>
        internal static string issue_temp_ice {
            get {
                return ResourceManager.GetString("issue_temp_ice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open windows.
        /// </summary>
        internal static string issue_temp_sweat {
            get {
                return ResourceManager.GetString("issue_temp_sweat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the curtains or apply sunscreen if you are sitting in the sun light.
        /// </summary>
        internal static string issue_uv_what {
            get {
                return ResourceManager.GetString("issue_uv_what", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the windows and doors to ensure drafts, you can also try to remove the source of the smell such as food or garbage.
        /// </summary>
        internal static string issue_voc {
            get {
                return ResourceManager.GetString("issue_voc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are the causes of bad indoor climate? : The room itself is an influence on how well the indoor climate is. The most important factors are whether there is poor ventilation and if there are too many people in a room. In addition, there are also some minor factors such as the rubbish bin is full and there is wet clothes in the room..
        /// </summary>
        internal static string q_climate_causes {
            get {
                return ResourceManager.GetString("q_climate_causes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How does CO2 affect you? : Carbon dioxide is a gas produced by the combustion of organic materials and fossil fuels. CO2 results from animals and humans exhaling. CO2 is found naturally in the atmosphere. Carbon dioxide in a high concentration reduces the amount of oxygen in a room, thus causing fatigue..
        /// </summary>
        internal static string q_co2 {
            get {
                return ResourceManager.GetString("q_co2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How does humidity affect you? : Humidity, also known as relative humidity, is a term for how much moisture is in the air. The amount of moisture depends on the temperature and is stated in %. Therefore, the air during a hot summer day can contain much more water than on a cold winter day, even if they have the same relative humidity. Humidity begins to affect you when it gets too high. The amount varies with over 60% during summer and 45% during winter. When it gets too high, there is too much water in the  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string q_humidity {
            get {
                return ResourceManager.GetString("q_humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is Indoor climate? : Indoor climate is a term for the environment in a room or building. The environment may be too cold, have poor acoustics or poor ventilation, all of which lead to a poor indoor climate..
        /// </summary>
        internal static string q_indoor_climate {
            get {
                return ResourceManager.GetString("q_indoor_climate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How does light affect you? : Too little light can affect you when you are reading, as it can make it difficult to focus. However, too much light can make it difficult to read and give you a headache..
        /// </summary>
        internal static string q_light {
            get {
                return ResourceManager.GetString("q_light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How does sound affect you? : A moderate background sound can increase creativity, if what you are working with does not require much focus. However, there are problems with high sound levels if they continue for a long time, as it may damage the hearing, cause irritation and irritation..
        /// </summary>
        internal static string q_sound {
            get {
                return ResourceManager.GetString("q_sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How does temperature affect you? : At high temperatures, it becomes difficult to get rid of the body heat. This causes you to sweat more and causes discomfort. If it gets too hot you can faint and get heat strokes, this is especially a problem with high humidity. At low temperatures, you start to get tired, feel discomfort and lack of coordination..
        /// </summary>
        internal static string q_temperature {
            get {
                return ResourceManager.GetString("q_temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is UV? : ?????.
        /// </summary>
        internal static string q_uv {
            get {
                return ResourceManager.GetString("q_uv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How does VOCs affect you? : VOC, also called volatile organic compounds, is a collective term for the various organic chemicals. They have a low boiling point and are therefore a gas at room temperature. For this reason, there are higher measurements of VOCs in the summer. Most VOCs can be smelled and are released by paint, glue, cooking, leftover food, etc. An excessive amount of VOC in the air of the room can cause irritation and discomfort..
        /// </summary>
        internal static string q_voc {
            get {
                return ResourceManager.GetString("q_voc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove IP.
        /// </summary>
        internal static string remove_ip {
            get {
                return ResourceManager.GetString("remove_ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove room.
        /// </summary>
        internal static string remove_room {
            get {
                return ResourceManager.GetString("remove_room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        internal static string room {
            get {
                return ResourceManager.GetString("room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Room.
        /// </summary>
        internal static string room_selector {
            get {
                return ResourceManager.GetString("room_selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room settings.
        /// </summary>
        internal static string room_settings {
            get {
                return ResourceManager.GetString("room_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
    }
}
